version: "3.8"

networks:
    nginx_network:
        external: true
    internal:

services:
    credo-tz-app:
        image: adhocore/phpfpm:8.1
        container_name: credo-tz-app
        working_dir: /app
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - '.:/app'
            - './docker/php/overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        depends_on:
            - credo-database
    credo-tz-app-nginx:
        image: nginx:alpine
        container_name: credo-tz-app-nginx
        restart: always
        working_dir: /app
        networks:
            - internal
            - nginx_network
        ports:
            - "9071:80"
        volumes:
            - .:/app
            - ./docker/nginx/credo-tz-app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - credo-tz-app
    credo-database:
        image: postgres:11.1-alpine
        restart: always
        container_name: credo-database
        working_dir: /app
        networks:
            - internal
            - nginx_network
        environment:
            - POSTGRES_USER=oauth_user
            - POSTGRES_PASSWORD=UYaRCA7emd2szH47
            - POSTGRES_DB=users
        volumes:
            - .:/app
            - ./credo-database:/var/lib/postgresql/data
        ports:
            - '8050:5432'
    credo-tz-app-composer:
        image: composer:latest
        container_name: credo-tz-app-composer
        working_dir: /app
        command: update --ignore-platform-reqs
        volumes:
            - .:/app
        restart: on-failure
        depends_on:
            - credo-tz-app
volumes:
    credo-database:
        driver: local
